# Generated by Django 3.2.15 on 2023-03-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('upwd', models.CharField(max_length=50)),
                ('uage', models.IntegerField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
