# Generated by Django 3.2.15 on 2023-03-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HTTPReauestApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='uemail',
        ),
        migrations.AlterField(
            model_name='users',
            name='uage',
            field=models.IntegerField(max_length=20, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='users',
            name='uname',
            field=models.CharField(max_length=50, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='users',
            name='upwd',
            field=models.CharField(max_length=50, verbose_name='密码'),
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
