# Generated by Django 3.2.15 on 2023-03-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HTTPReauestApp', '0002_auto_20230322_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uage',
            field=models.IntegerField(max_length=20, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='users',
            name='uemail',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
    ]
