# Generated by Django 3.2.15 on 2023-03-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20230315_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
    ]
