# Generated by Django 3.2.15 on 2023-03-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20230315_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-age', '-name'], 'verbose_name': '作者', 'verbose_name_plural': '作者'},
        ),
    ]
